### ISSUE TITLE
Optimize projectile collision detection

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#130]
Basic algorithm was copied from vanilla back in A10 or so and somewhat outdated. Could use optimization to save on performance. Potential things to investigate:

- Use better methods to find collidable objects, avoid checking motes and such
- Use HashSet to store previously checked cells 
- Alternatively, use an anti-aliasing algorithm like [this](https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm) to generate a list of cells to iterate through. Advantage would be greater accuracy over current raycast method (cells are skipped entirely if bullet travels <0.2c through the cell, e.g. on a corner). Unknown impact on performance.

**Comment by ProfoundDarkness** [comment]
Observation 1: RimWorld now has a cache of cover objects (things) by cell in class Verse.CoverGrid.  Might not have existed when original projectile code was written.  Could probably get a decent speed up by using this in current projectile related code instead of iterating over all things in each cell (which can include motes and junk).  Instead one would ask CoverGrid for the cover thing at a given cell, either get a thing that offers cover or nothing.

Observation 2: Using HashSet to avoid rechecking cells instead of using a list should offer some speedup in current projectile related code, particularly for longer projectile paths.  Best of all if the membership list in current code is ONLY used for membership testing then the change is minute, just change List<> to HashSet<>.

Observation regarding line drawing for projectiles:
This would be a big change and might end up throwing out current logic.

It looks like the line of sight code in RimWorld (Verse.Gensight.LineOfSight) looks similar to fast line drawing code (where cells would be pixels).  By fast I mean that it doesn't care how well the 'pixel' fits, just detects that the line should pass through the 'pixel'.

The problem with the line drawing code is in order to quickly check cells, cells are the increment but now bullet speed becomes variable.  That makes it harder to tell what the bullet height should be at any given cell.

Could possibly use the 'brightness' of the 'pixel' (in anti-aliased line drawing) to determine how far the bullet traveled in that cell.  But that doesn't solve the issue of the bullet's speed now being somewhat variable.

This method could be used to generate a list of cells which the bullet will pass through (ending calculation with ground impact/range end and not at first cover impact) and then fall back on something like the current code to determine what the bullet hits over time.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/00b5ade6c831903510fa81d22fb0faa459100156 Started work on larger LoS overhaul. Currently redid the way partial cover obstructions are done, should be much more reliable now that old raycast method has been replaced with bounding box collision detection along entire line of sight.

The same principle can be applied to projectile collision detection: use vanilla LoS algorithm (which is doing something like the anti-aliasing thing mentioned above) to calculate a set of cells between the current projectile position and the one next tick, then check for bounding box collisions.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/b8f9014ce3a6018137b628ae8095aab612821ca2 Implemented new collision detection method based on anti-aliasing line instead of raycast and using bounding box for collision detection. Should yield improvement in collision detection accuracy, albeit at the cost of speed (only really noticeable with very large numbers of bullets at 3x or more speed).
