### ISSUE TITLE
Default Outfit contains shield/Pawns will equip Ballistic shield despite having 2handed weapon

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#137]
Default outfits (Anything and Nudist) contains shields (ballistic and energy) by default. 
Pawns will equip ballistic shield despite having 2h weapon. This doesnt give you a "Ranged weapon with shield warning" but instead spawns you console with errors and slows the game down.
Pawns also equipd Balistic shield despite it being disallowed in their outfit

https://pastebin.com/8HxSa7z2

**Comment by NoImageAvailable** [comment]
I'm not sure removing shields from the anything outfit is possible, since it includes every piece of apparel in the game. I think the best we can do here is add additional warnings when equipping two-handed weapons with shields and an alert that pops up whenever a pawn is prevented from using his weapon.

Fixing the hunting error is easy enough by adding an additional check. I've modified the code to include CE shields when checking for energy shields on hunters and changed the "Hunter has shield" alert to reflect that.

**Comment by NoImageAvailable** [comment]
Should be fixed as part of https://github.com/NoImageAvailable/CombatExtended/commit/f1d6f2d40658020d8782db8248ebb1f9620f5065
