### ISSUE TITLE
Taming pickup-drop loop

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#141]
Testing on v0.2.0-beta

One of my colonists, with a loadout created with the handy "make loadout" button (which defaults to dropping over 10 raw food), tried to tame a muffalo with berries and got stuck in a loop picking up a stack of 14 (which brought her to 24), dropping the excess, then deciding she didn't have enough and picking them up again.

Changing her loadout to allow 30 raw food served as a work-around.

**Comment by ProfoundDarkness** [comment]
NOTE: The PR I submitted changes the purpose of the generic loadout for raw food (to my mind).  So now an open question is if we should still be including that by default and if so how much nutrition to target or how many things?

**Comment by NoImageAvailable** [comment]
I don't see a reason to include raw food in default loadouts except paired with regular meals, since the primary purpose is to allow stocking of food for the day. If the taming job is handled separately we should be good to remove raw food from default loadouts.

**Comment by ProfoundDarkness** [comment]
OK.  I'll remove the default flag from the raw food generic def.  Closing this as the bug seems to be fixed.

**Comment by shoobug** [comment]
Getting this error with the June release. Happens when colonists need food to tame, or getting items for their loadout. Was able to use the workaround above for my handlers, but they still get stuck occasionally. Began doing this at the start of my new game.

Pawns just approach what they need, and randomly get stuck in a pickup loop returning the error "10 jobs in 10 ticks". Some pawns behave normally, but others get stuck standing there popping the debug log endlessly until they have something better to do.

The first one pops, then the second repeats itself.
Error:
> Viper started 10 jobs in 10 ticks. List: (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , and (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture)  lastJobGiver=, curJob.def=WaitMaintainPosture, curDriver=Verse.AI.JobDriver_WaitMaintainPosture
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

>Viper started 10 jobs in 10 ticks. List: (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture) , and (TakeInventory A=Thing_Kibble357598) (WaitMaintainPosture)  lastJobGiver=, curJob.def=WaitMaintainPosture, curDriver=Verse.AI.JobDriver_WaitMaintainPosture
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by artfaal** [comment]
Same problem

**Comment by anon54** [comment]
This problem (or something "related) still exists. Just encountered it in the last two playthroughs dealing with the pickup of hay for use with animals.

**Comment by NoImageAvailable** [comment]
You're running into the smarter food selection compatibility issue, not a CE bug. Read the OP people, there's a reason SFS is listed as a known conflict.

**Comment by anon54** [comment]
I never saw SFS listed anywhere as not compatible.

**Comment by NoImageAvailable** [comment]
It's right in the OP of the forum thread, in the compatibility section
