### ISSUE TITLE
Rescued space refugee desperately wanting equipment

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#142]
Testing on v0.2.0-beta

My colony rescued a space refugee. When she was able to walk, she mined her way through the wall of her room, walked to my stockpile, and grabbed a knife.

Fortunately, Rimworld isn't a slasher movie, so she then went back to bed and lay down to rest instead of killing my colonists one by one. But still.

I'm not sure if this applies to anyone other than space refugees. I haven't seen it happen, but that doesn't mean it won't. I'll update this post if it does.

**Comment by NoImageAvailable** [comment]
In the mod settings, do you have the auto-equip ammo option enabled? (On by default)

**Comment by Maeyanie** [comment]
Yes, I do. All options are set to their defaults except for enabling right-click ammo selection.

**Comment by dvalroth** [comment]
That's a bug that came up when Sky was maintaining it. Pawns were somehow getting raid AI assigned so they sapper their way to what they want rather than using doors like rational people.

**Comment by Maeyanie** [comment]
The fact that they're trying to steal stuff in the first place is a bug, really. In vanilla they just are thankful to be able to walk freely again (unless they changed that since the last time I played vanilla, it has been a while).

I think I got something similar to happen with a released prisoner; he decided he wanted some clothes so picked them up on his way before leaving the map. Didn't bash through any walls, though, just picked up stuff that was on the ground outside a stockpile, so that might be legit.

If it is the same as the problems in Sky's version, it may also happen with sieging enemies and visitors if they spawn without a weapon, but I haven't had those happen while testing yet so can't report on it either way.

**Comment by NoImageAvailable** [comment]
I know sky's additions included new AI behavior where raiders would pick up nearby weapons when out of ammo. IIRC it also included some behavior related to picking up apparel. My guess is its missing a sanity check somewhere so when you rescue a pod survivor it kicks in and tells him to find a weapon and ammo.

An easy way to check would be to start a new map, recreate the scenario then try again with the auto-equip ammo option turned off. If turning it off fixes it then we know for sure that's what's causing it.

**Comment by ProfoundDarkness** [comment]
This was a bug I reported (or co-reported) in CR and someone else fixed... pretty sure CE branched from CR before that fix happened.

Also IIRC it's a stock RimWorld behavior for some pawns (ie escaped prisoners, possibly visitors) to try and fetch a weapon automatically if they don't have one... though also IIRC they really only look in the same 'room' they are in and will path around stuff just fine in stock.

I have some other vague memories I'll explore a bit and report back...

Oh, one other detail, there was another mod with CR that amplified the problem greatly, Hospitality IIRC.  Part of the bug in CR combined with Hospitality would see visitors dig through your base everywhere they went.

**Comment by Maeyanie** [comment]
That's possible, I did install Hospitality in my minimal test environment after getting some red debug text on load relating to it not being installed. I'll do some more tests (without hospitality, without auto-equip ammo, without either) and see what happens.

**Comment by ProfoundDarkness** [comment]
I should add... Hospitality made things worse but wasn't the source of the issue in CR.  When CR got fixed even with Hospitality pawns weren't pathing through my base's walls anymore.

**Comment by Maeyanie** [comment]
With hospitality off and auto-equip ammo on, the rescued refugees walked off no problem.

With hospitality on and auto-equip ammo off, they also walked off, but gave the following exception:
```
Exception in Verse.AI.ThinkNode_PrioritySorter GetPriority: System.NullReferenceException: Object reference not set to an instance of an object
  at CombatExtended.JobGiver_UpdateLoadout.FindPickup (Verse.Pawn pawn, CombatExtended.LoadoutSlot curSlot, Int32 findCount, CombatExtended.ItemPriority& curPriority, Verse.Thing& curThing, Verse.Pawn& curCarrier) [0x00000] in <filename unknown>:0 
  at CombatExtended.JobGiver_UpdateLoadout.GetPrioritySlot (Verse.Pawn pawn, CombatExtended.ItemPriority& priority, Verse.Thing& closestThing, System.Int32& count, Verse.Pawn& carriedBy) [0x00000] in <filename unknown>:0 
  at CombatExtended.JobGiver_UpdateLoadout.GetPriority (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
```

I'm not sure if I had exception popups on or off when I had hospitality disabled, since I do recall getting some errors related to not having it. So it's possible the same message happened there and I just didn't notice.

Full log:
https://gist.github.com/HugsLibRecordKeeper/24982dd8c9a921ebfe8a627c3e976bf3

(The earlier exception I'll be posting a different report about, if it's reproducable.)

**Comment by NoImageAvailable** [comment]
So to clarify, the issue only occurs with Hospitality installed?

**Comment by ProfoundDarkness** [comment]
Testing with latest hospitality installed... (CE is at the bottom of my load order)

I haven't been able to replicate the JobGiver_UpdateLoadout issue.  I'd really only expect that code path for pawns that are colonists...

I was able to replicate the unarmed space refugee trying to dig through a wall to get a knife.

Exposed a bug in the no loadout codepath for pawns automatically fetching ammo for their equipped gun and not having the inventory space.  Ends up in a loop with the pawn standing over/near the ammo they want and starting 10 jobs in 10 ticks.

Unknown if bug (request input) - visitors fetching stuff from rooms they aren't in.  Members of the test visitor group happily walked into my storage room (4 walls and a closed door) and cleaned out my ammo supplies.  I've come to accept that happening if my stuff is 'outside' or otherwise in the same 'room' as a public space (table with chairs) but not so much if my stuff is not in a public space/outside.

Going to see what I can replicate without Hospitality.

**Comment by ProfoundDarkness** [comment]
Without Hospitality replications:

-Unarmed space refugees still tried to drill through walls to get at a melee weapon.  However in Hospitality it almost always happened while it took about a dozen refugees to get a couple to start digging through the wall.

-Visitors didn't try to steal anything from storage room.

-Visitor pathfinding is bad (this was fixed in CR after CE branched off) - when I used god mode to remove a wall from the storage area visitors started digging through my base to get to the storage area and grab ammo and such which was now 'outside'.  They shouldn't opt to dig through my walls like that.

**Comment by NoImageAvailable** [comment]
It sounds to me like at some point during the "arm yourself" routine the pathfinding enables visitors to dig through walls. Might need to track that place down and disable digging, since non-colonists should never attempt to dig through a wall in order to pick up more ammo.

Regarding visitors fetching stuff, I think it makes sense that visitors would equip themselves during battle but not on a regular visit. Ideally they should check for the following:
- In combat situation (maybe check if there is a hostile spawned pawn outside fogged area)
- The ammo they're picking up is not reserved by a colonist, nor in a colony-owned storage (either stockpile or equipment rack)

**Comment by Maeyanie** [comment]
On v0.3.1-beta, I just had a Hospitality visitor mine his way through a wall looking for ammo, with auto-equip ammo enabled.

Haven't seen anyone go for guns since that patch though, so it's definitely improved.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/43883d5c67e1bd43b0010d787d6a6a6e8bc08257 I disabled use of the goto force job. It seems silly that pawns would dig through or bash open doors to get to ammo in the middle of combat.

Todo: disable visitors from grabbing player-owned ammo entirely. They have no business stealing player supplies, period.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/3625b66cbdaf919516eba24e2ae459d155e0990e Commented out the sections dealing with apparel acquisition. While a nice idea on paper, in practice you'll never really have an opportunity to see this in effect that doesn't involve random raiders dashing for your stockpile to steal your pants.

**Comment by NoImageAvailable** [comment]
Recent changes should hopefully fix the worst of the errant behavior, removing it from 1.0 milestone but leaving it open since its not fully resolved yet.

**Comment by NoImageAvailable** [comment]
Haven't seen any errant behavior playing several test games with Hospitality and given nobody else reported this I'm assuming it is fixed now.
