### ISSUE TITLE
Pawns target nearest enemy even if it is obstructed by an object

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#21]
Small enemies like boomrats and squirrels cannot be hit if they are close to an embrasure or behind a rock. If the closest enemy is obstructed in this manner, colonists will stand idly instead of targeting something else.

**Comment by ProfoundDarkness** [comment]
Got an idea on this... thinking of replacing the method call GenClosest.ClosestThing_Global in AttackTargetFinder.BestAttackTarget (which is called by BestShootTargetFromCurrentPosition which is called by JobDriver_Wait.CheckForAutoAttack) with a variation on ClosestThing_Global where if the target can't be hit due to cover it will reject it as a target (and thus JobDriver_Wait will never know about it).

I could potentially just add the logic into ClosestThing_Global but other non-combat stuff is bound to use that so a new method with lots of copy-code seems the apt path.

**Comment by NoImageAvailable** [comment]
Merged https://github.com/NoImageAvailable/CombatExtended/pull/111, should be fixed now
