### ISSUE TITLE
Bows firing stone arrows inappropriately

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#217]
Testing on v0.17.0.4.2-beta.

One of my colonists is using a bow, and is only carrying steel arrows. The text by the verbs says it's loaded with stone arrows, and when someone is hit, the wound says it was done by a stone arrow. Using right-click ammo selection to tell it to use steel arrows doesn't help.

I wasn't able to do extensive testing on this as shortly after the combat where I noticed this, my medic went berserk and murdered the whole colony in their sleep, but I'll update when I get the chance.

**Comment by NoImageAvailable** [comment]
Magazine-less weapons weren't setting their current ammo properly when selecting from the ammo gizmo. Also the check for reducing ammo wasn't set up to update selected ammo type when it wasn't available, meaning any ammo could be used to fire any projectile. Should both be fixed in https://github.com/NoImageAvailable/CombatExtended/commit/daf23da7aef66cbe6a9f507da418dce1e34f0d29
