### ISSUE TITLE
Reload report string has incorrect ammo

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#235]
1. Have an out-of-ammo weapon with FMJ selected.
2. Have operator have AP or HP ammo in inventory.
3. Hit reload button with ammo still set to FMJ.

Weapon will load AP/HP ammo but report string says its loading FMJ.

**Comment by Alicecomma** [comment]
The issue is due to the method _after_ the timer deciding what ammo to load/whether there is any ammo to load to begin with. This method should be split up into a part deciding whether anything could be loaded and what ammo to load (pre-timer) and a method actually performing the reloading (post-timer).
