### ISSUE TITLE
Handling task/inventory issue

### ISSUE THREAD

**Issue by HairyMilkshakes** [NoImageAvailable/CombatExtended#260]
Hi, not sure if it's completely related to the way inventory is handled by CE, but here are errors from the log:

`Jenni started 10 jobs in 10 ticks. List: (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , and (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture)  lastJobGiver=, curJob.def=WaitMaintainPosture, curDriver=Verse.AI.JobDriver_WaitMaintainPosture
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
`

`CE tried throwing invalid taunt for Bud
Verse.Log:Warning(String)
CombatExtended.Verb_LaunchProjectileCE:WarmupComplete()
CombatExtended.Verb_ShootCE:WarmupComplete()
Verse.Stance_Warmup:Expire()
Verse.Stance_Busy:StanceTick()
Verse.Stance_Warmup:StanceTick()
Verse.Pawn_StanceTracker:StanceTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
`

I do have **Colony Manager** enabled as well.

**Comment by NoImageAvailable** [comment]
The 10 jobs in 10 ticks thing I can confirm. The taunt warning is a completely unrelated issue though.

**Comment by HairyMilkshakes** [comment]
Here's a way to reproduce it:

1. Make kibble stacks
2. Have someone prioritize handling

They'll go to the stack, remove a portion of the kibble, and repeat. Sometimes they stand on the kibble without doing anything. When you open their inventory to check, you can see that they are constantly taking and removing kibble in small amounts.

**Comment by NoImageAvailable** [comment]
The vast majority of the time handling works fine though. I've also seen the issue appear with other items that were unrelated to handling, so I highly doubt its related to the taming job.

**Comment by HairyMilkshakes** [comment]
Interesting. I've also see those kinds of exceptions. Hope you can fix it soon.

**Comment by HairyMilkshakes** [comment]
Played around with disabling mods a bit more and the first error went away after I disabled WM Smarter Food Selection. However, it's now showing on the top-left hand corner as a notification that "___ can't do taming job because of a full inventory"

**Comment by NoImageAvailable** [comment]
So as luck would have it I obtained a savegame with the bug. Now after a bunch of prodding it looks like the issue is somehow the pawn's inventory "looses" specific items. They show up in the gear tab but by the time the loadout job is called the item is no longer recognized as being in inventory. Printing out the entire contents of the ThingOwner doesn't list the bugged item and the entire logic breaks down from there.

**Comment by NoImageAvailable** [comment]
Okay, so turns out I was on the completely wrong track with the above. The reason the item is gone from inventory is because JobGiver_DropUnusedInventory removed it. That one is responsible for dropping excess food from tamers' inventories after a certain timeout period (hence why taming jobs were bugging out) as well as drugs a pawn is not allowed to have by vanilla logic (in my case someone high on go-juice was trying to pick up a bottle while still high).

In those cases pawns will try to pick up the missing items only to have the game immediately force them out of their inventory, creating an infinite loop.

Potential solution: remove the JobGiver from ThinkTree entirely. Roll still wanted functionality for removing excess raw food into HoldTracker by adding a timeout period for anything picked up via taming job. Get rid of drug functionality entirely since it is superseded by loadouts.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/c0b06eb3c3a14504cd0fc0bb23a28d65543cda73 Attempted fix, tested with drugs but still need to test with tamers to ensure hold records are getting cleared properly.
