### ISSUE TITLE
Major micromanagement problem with animal training.

### ISSUE THREAD

**Issue by JustALittleCrazyTalk** [NoImageAvailable/CombatExtended#268]
Because of the bulk system pawns will refuse to pick up food to train animals with, meaning pawns have to be told to drop items, train the animals, then pick the items back up. Bulk fills up with only basic clothing and weapons, no special loadout of any kind.

**Comment by NoImageAvailable** [comment]
The solution here is to add a tactical vest or backpack if you're having problems with bulk. If you don't like the micro don't overload your tamer's inventory, give them lighter weapons etc.

Closing this since feedback, while always appreciated, should go in the forum thread/Discord, not the issue tracker.
