### ISSUE TITLE
Backpacks should have material/quality properties

### ISSUE THREAD

**Issue by moosestrangler** [NoImageAvailable/CombatExtended#279]
Right now backpacks are always made from cloth and have no quality property.  This means they cant be stored in stockpiles with quality restrictions or made from leather/wool/devilstrand. Treating backpacks like other clothing with quality and material properties would fix these.

**Comment by AdmiralKew** [comment]
For now, get this file here:
https://ludeon.com/forums/index.php?topic=33461.msg348310#msg348310

**Comment by NoImageAvailable** [comment]
Would require some relatively in-depth changes to how the bulk stat is calculated to make this possible. Also potential issues with e.g. Devilstrand backpack (not) providing additional armor. Seems too much effort for too little gain.

**Comment by Alicecomma** [comment]
_Since load bearing gear count as clothing, is there some way to get around the lack of a quality flag for them in the outfit template configuration (and storage, though a second stockpile can take care of that)? If you for example tell a colonist to only wear legendary clothes, they will not equip backpacks/tac vests since they don't have a quality (or rather, they seem to have a hidden one; if you set the lower limit low enough, I'm guessing at "normal", they will be equipped). I tried adding them to the loadout template instead, but that just resulted in my colonist putting them unequipped in their inventory._

(From the forum posts)
