### ISSUE TITLE
Loadout suggestions

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#34]
The original "Nothing" loadout should not be alterable.
Add a generic option, ie. "carry x number of meals"
Interface with stock drug policy system's take to inventory feature
Add a copy loadout function, would save a lot of clicks in many situations.
Allow sorting of the assignment screen by loadout, for easier use.

**Comment by RenaudF** [comment]
Give weapons in the loadout an auto-pick ammo option

**Comment by ProfoundDarkness** [comment]
I've been pondering generics a bit in connection to other systems.

We could either do infixing/detours to engage with other systems (ie drug) or allow generics and a flag to handle the situation.  There are two parts to this.

Part 1 - Generics: I envision these (at least as a starting point) as being able to select a category much like how items are nested in categories for storage zone settings.  What shape that takes exactly is left for later.  Using the already available category system seems like the simplest method of handling things from a user perspective since they will probably already be familiar with item hierarchies.

Part 2 - Autofill loadout slot flag: The new flag would indicate if the pawn should try to fill the need or not.  This seems like the simplest path of implementation to make it so that pawns can pick up something (specific or generic) and the loadout system won't try to drop it later but nor will the loadout system try and fill that configuration.

Between these we could (By default when making a new loadout object) include two loadout slots, one for meals (category) (or even food) and another for drugs.  The new loadout items would have the flag indicating not to auto fill but that also means they wouldn't be auto-dropped.  Then we don't have to lift a finger to interact with the other systems.

**Comment by NoImageAvailable** [comment]
Regarding categories, the first prototypes of the loadout system used the category menu instead of individual Things for assignment. It was very clunky and convoluted in addition to having some significant practical issues such as how to assign quantities. For those reasons it was discarded in favor of the current implementation.

**Comment by ProfoundDarkness** [comment]
Items which, to my mind, have been dealt with as of commit #105 or before:
*The original "Nothing" loadout should not be alterable.
*Add a generic option, ie. "carry x number of meals" (Generics which are Lambda based)
*Interface with stock drug policy system's take to inventory feature (can use a Generic that ignores drugs so that the drug policy system's take to inventory won't be auto-dropped).
*Add a copy loadout function, would save a lot of clicks in many situations.

Things that haven't been done by that point:
*Allow sorting of the assignment screen by loadout, for easier use. (low hanging fruit after so much time on loadouts, adding to my list).
*create loadout from current inventory (I haven't had a good idea for this UI wise yet so suggestions welcome.)

Not sure where this fits:
*inclusive/exclusive loadouts so pawns don't auto drop other items

Special mention:  auto-pick ammo option per gun/loadout
The new generics and some other changes to loadout.  After one picks a gun one can pick a generic Any Ammo for <gun> from the same button as they can pick individual rounds.  The generic currently auto adds a full clip when picked.  Would only take a small tweak to auto add this if it is deemed desired.  Personally I'd like to manually pick my ammo.

Another possible alternative is to extend the system (if I can figure out how it works) where a pawn without a loadout will auto fetch x clips worth of Any Ammo (generic).  Could extend that so that pawns WITH a loadout but no ammo for that gun defined would auto fetch as if they didn't have a loadout... ?

**Comment by ProfoundDarkness** [comment]
Pretty sure most of the suggestions in this list have been implemented.  If not feel free to open a new issue specific to the suggestion not appropriately implemented.
