### ISSUE TITLE
Suppression immunity

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#37]
Pawns with certain (existing - psychopath? - and/or new - nerves of steel?) traits could be immune to suppression. Can pawns acquire traits throughout the game? Could also make it as a hediff (is that what it's called?) after taking so much suppression they don't care so much (kinda like an experience system).

Could certain backstories also influence a pawn's tolerance to suppression?

Pawns under the influence could also become immune to suppression, would be nice to see more use cases for the drugs.

**Comment by frenchiveruti** [comment]
> Can pawns acquire traits throughout the game? 
If this is a serious question, they can't acquire new traits, at least not via "vainilla methods", although the "dev mode" allows the user to "insert" a new trait to a pawn.

**The "experience" method for not getting suppressed** should be taken with a lot of care, because the user can then abuse of it by simply placing the pawns infront of a friendly line of fire, but behind a set of PowerArmor, and with low caliber ammo. I think it would be much trouble to implement for the benefit it brings and the duration of an average colony.

**Traits** that makes the pawns less prone to suppression seem like a good and interesting idea, such as "brave" or "nerves of steel". Maybe the bigger the trait (like brave < nerves of steel), the bigger the chance to _not_ get suppresed.
Certain backstories could be like the one that are combat related, such as space marine (_IIRC_).

**Comment by RenaudF** [comment]
Ye experience could be very complicated and totally not worth the trouble. Just out of curiosity:

`the user can then abuse of it by simply placing the pawns infront of a friendly line of fire, but behind a set of PowerArmor, and with low caliber ammo`
Isn't there always a chance the ammo could inflict bruising damage?
Doesn't the armor durability go down when it takes hits though?

**Comment by frenchiveruti** [comment]
> Isn't there always a chance the ammo could inflict bruising damage?
> Doesn't the armor durability go down when it takes hits?
Yes but on more advanced colonies, you can spare a few medpacks and also a shitty power armor that a previous raider left to train a hidden skill that there's no way to raise other than getting constantly shot, I just stated what would I do. And bruises or even gunshots are not that "bad" when you have a level 16+ doctor working around.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/42c0e0c8ca21bed8ee5e463bee646d60e546a0ca Pawns now have suppressability stat acting as a multiplier on all suppression received. Scales with consciousness (less conscious pawns are less affected by suppression) and is reduced by certain drugs (yayo, go-juice). Pawns can spawn with traits cowardly, brave and fearless, which increase, decrease and negate suppression respectively.
