### ISSUE TITLE
Option to remove parry limit

### ISSUE THREAD

**Issue by JCDentonNSF** [NoImageAvailable/CombatExtended#384]
Never saw the point of limiting how many parries a pawn could perform, an option to disable it (if that's even possible) would be nice.

**Comment by NoImageAvailable** [comment]
Parries are limited because it makes no sense from a gameplay perspective (parry is meant for single target defense, dodge for multi-target) nor from a realism perspective (you can't parry 5 people at once unless you're a Jedi).

And let's not forget that every toggle you implement is two features you don't.
