### ISSUE TITLE
Records don't include turret kills / bullets fired.

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#40]
Kills from manned turrets are not added to the using pawn's records.

**Comment by frenchiveruti** [comment]
More like an eyecandy feature.
Do you guys have tags in this git?

**Comment by NoImageAvailable** [comment]
Does this apply to vanilla mortars as well? Curious if this is a vanilla issue or specific to CE.

**Comment by Alicecomma** [comment]
This would likely require detouring:
```
// Verse.Pawn_HealthTracker
public void Kill(DamageInfo? dinfo, Hediff hediff)
```
.. and adding an additional "is turret" check, then providing code to check for the turret handler and sending that Pawn along as killer.
```	
if (dinfo.HasValue && dinfo.Value.Instigator != null)
{
	Pawn pawn = dinfo.Value.Instigator as Pawn;
	if (pawn != null)
	{
		RecordsUtility.Notify_PawnKilled(this.pawn, pawn);
	}
}
```

**Comment by Alicecomma** [comment]
I attempted the detour however I got stuck at the following line:
```
this.pawn.relations.Notify_PawnKilled(dinfo, map);
```
Since it is an internal method call which I personally don't have experience with detouring / handling in detours.

**Comment by NoImageAvailable** [comment]
According to forum reports this also affects records of bullets fired.

**Comment by Alicecomma** [comment]
In fact, this issue was due to turret projectiles having caster = _the turret_, fixed by the existence of Verb_LaunchProjectile.ShooterPawn to know the operator of the turret. ShooterPawn used CE_Utility to determine who the operator was however this method casted the turret to Building_TurretGun, while Building_TurretGunCE (the class of CE turrets) is a child of Building_Turret, NOT _TurretGun.

**Comment by NoImageAvailable** [comment]
Merged the PR, should be fixed now
