### ISSUE TITLE
Apply stopping power

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#605]
Projectiles should be updated with stopping power. Proposed formula: damage * 0.1

**Comment by PajamaBinLaden** [comment]
Stopping power is mostly a myth, though?
http://gunbelts.com/blog/why-stopping-power-is-a-myth/

**Comment by NoImageAvailable** [comment]
It's a vanilla mechanic now though

**Comment by dvalroth** [comment]
I could see like the beanbag shotgun having "stopping power", that's kinda the point of it, but yeah most bullets either don't have all that much force behind them or have so much that they just go right through you or make you explode. In terms of preventing advance, that's already covered by suppression. Perhaps RPGs and recoilless rifles? As a mechanic I could see it being used for the likes of Bolters, or maybe the cryptobiosys or gravity guns, but it doesn't seem like something that needs to be universally present.

**Comment by jtgibson01** [comment]
Stopping power was most likely added to vanilla due to the new mechanic that being engaged in melee prevents use of a firearm.  It is of course much more difficult to shoot someone who is actively resistrant at point-blank range, but someone does not immediately move to start butt stroking.  (God I love that expression.  It sounds so dirty. =P)

Thus, unless we were to re-implement point-blank shooting and give pawns the option of switching to melee or continuing to fight hand-to-hand (presumably whether melee DPS*chance to hit is higher than close ranged DPS*chance to hit), stopping power probably needs to be there as a balancing factor.

Then again, though, the strategy of firing over someone's shoulder is brutally effective in the vanilla game right now, when in reality standing behind someone in a pitched melee to shoot at the person just past them is a recipe for a friendly fire disaster.  So, that might need to be looked at too.

**Comment by jinlan** [comment]
What about make stopping-power pain related? Bigger pain bigger stopping-power.

**Comment by NoImageAvailable** [comment]
After thinking on it I think we're better off without stopping power. Reasoning:
- Suppression already serves as a way of preventing advances
- Stopping power relies on getting hits in, meaning it's effectiveness scales with range. Close range is already lethal and stopping power means you're much more likely to get hit, then hit again before you can react.
- Weapons already work fairly well in their respective range brackets and melee is more about having shields that prevent getting hit to begin with, meaning stopping power has no effect on melee and only disrupts ranged balance for no reason
