### ISSUE TITLE
Grenades fly too high and far  if the target has big body size.

### ISSUE THREAD

**Issue by michail-r-borovoy** [NoImageAvailable/CombatExtended#609]
If target has body size big enough (for me it works on 8 point) grenade will be thrown with such velocity and power, so it will overfly the target, and will fly much longer distance then usually, missing the target
Body shape of the target was animal quadruped.

**Comment by N7Huntsman** [comment]
Seeing the same thing, even just aiming at the ground--I'm wondering if it has something to do with the grenade projectile speed suddenly bring so high.

**Comment by NoImageAvailable** [comment]
All projectiles follow an arc. The issue here is they aim center of mass and not the ground as you might expect from a grenade.

**Comment by Alicecomma** [comment]
Some possible fixes are to make an exception for explosives:

- Add a tag for grenades specifically to always aim at the tallest surface (non-pawn) on the target tile
- Make all explosives aim at the tallest surface of the tile rather than center of mass

Alternatively, always aim at C.O.M unless target is taller than 2 tiles:

- Bound the C.O.M including surface height - such that the height considered for C.O.M will always be 2f or smaller => an elephant standing on a 0.5f sandbag would be shot at height 1.5f.
- Bound the C.O.M using only the roof height - such that any shot will only be aimed between 0f and 2f. An elephant standing on a 0.5f sandbag would be shot at height 1.25f.

Currently, elephants (height ~4f?) on sandbags are shot at height 2.5f, also with grenades.

**Comment by NoImageAvailable** [comment]
>Add a tag for grenades specifically to always aim at the tallest surface (non-pawn) on the target tile

Grenades and other arching projectiles already use a flag to ignore partial LoS blockers on calculations, might be viable to extend this. Aiming at cover height/floor level might make sense for explosives in general (I can hear the inferno cannon whine already)

**Comment by Alicecomma** [comment]
Aiming at the floor would make most sense for timed explosives, but a tag would of course be best.

The thing with the C.O.M calculations is also for example the fact mounted pawns might have a larger height than 2f, so that'd need to be taken into account explicitly.

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/075a7dda9cae662145b3d1ce35f58070ce269ac5
