### ISSUE TITLE
Out of bounds exception on turrets

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#65]
Selecting a turret produces an error saying it couldn't draw a circle with the turret's range. Most likely caused by the turret range exceeding the maximum radius Rimworld can generate circles for.

**Comment by frenchiveruti** [comment]
Just by curiosity, what's that maximum radius?

**Comment by Alicecomma** [comment]
A maximum of 10000 cells can be in a radius.

**Comment by frenchiveruti** [comment]
Ah, it's an area count, interesting.
Thanks

**Comment by ProfoundDarkness** [comment]
Just a random thought but one could Harmonize the radius draw method (prefix), if the requested radius is within Rimworld's ability to draw, pass control to Rimworld code (probably faster since it's already cached some data).  If not then try to draw our own.  I didn't study the code long enough to have an idea of how to draw our own or how expensive it might be.

**Comment by ProfoundDarkness** [comment]
Changed a few variables in RimWorld's code and no more red error text.  The circles can look weird if a certain extra amount of areas aren't generated.
