### ISSUE TITLE
When pawns come back from travelling they will empty their inventory.

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#70]
Which is totally fine except for weapons and ammo. Can we make it so that they won't unload those?

**Comment by NoImageAvailable** [comment]
Shouldn't unload anything that's part of their loadout, really.

**Comment by Alicecomma** [comment]
Potentially fixed in https://github.com/NoImageAvailable/CombatExtended/commit/40ca7d697ce493505e79f276ae026fb1b3052a83. In this commit I made pawns take into account their loadout while unloading their inventory. They will still dump weapons and ammo however they are also prone to carry ammo that is not in their loadout.

Please report results.

**Comment by RenaudF** [comment]
If you make pawns dump everything thats not part of their loadout you're forcing the player to use the loadout system when sending pawns out on caravans which imo is a bad idea considering how unflexible it is in its current state.

**Comment by Alicecomma** [comment]
The problem with that is that a pawn can carry weapons and ammo that he can't use in his inventory because they're randomly distributed among the caravan, but at the same time it could be that the player wants those weapons/ammo in their inventory (which they could now just make a loadout for and it would work).

Basically there is no way to check whether the weapons/ammo in a pawn's inventory should be dropped or not besides checking whether the ammo fits in the current weapon OR checking the loadout system to see what the player specified.

**Comment by RenaudF** [comment]
Aye fair, I guess the pain will ease out when loadouts get easier to use.

**Comment by ProfoundDarkness** [comment]
Took a page from Alicecomma and added a JobDriver and xml targeting the pawn's empty own inventory behavior after Harmony proved too hard to maintain and understanding how what Alicecomma tried to do worked.  Tested behavior in PR #106 and pawn's didn't drop stuff they shouldn't be dropping as per their assigned Loadout/HoldTracker.  Closing.

**Comment by michail-r-borovoy** [comment]
Am not sure this is what is meanted to be, but sometimes pawns returns from travel starts just standing at the place with job "Unloading inventory" or somewhat.
@ProfoundDarkness : may you reopen this or i could open a new issue?

**Comment by ProfoundDarkness** [comment]
Reopening this by request for re-evaluation for A17.

**Comment by NoImageAvailable** [comment]
#193 should clear this up, please report back if this happens again
