### ISSUE TITLE
Recoil applied to first shot in burst

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#808]
According to reports on Discord, recoil seems to be applied to the first shot of a burst even though it shouldn't. This affects especially third-party patched semi-auto firearms which shouldn't be experiencing recoil at all but often have it specified for spreadsheet reasons.

**Comment by Alicecomma** [comment]
It's because someone moved the GetRecoilVec(ref rotationDegrees, ref angleRadians); from just before Vector2 spreadVec = report.GetRandSpreadVec(); to inside the MechanicalOnly calculations.

The whole method has been rearranged to the point it doesn't make logical sense anyways; many of these target- and angle shifts were intentionally sequenced. Currently, recoil isn't applied on any shot BUT the first shot.

**Comment by NoImageAvailable** [comment]
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/bcc67d1a7396de1f42e0986734513999d7ae6b8c

>Currently, recoil isn't applied on any shot BUT the first shot

Testing shows recoil applies correctly after each shot
