### ISSUE TITLE
HugsLib incompatibility

### ISSUE THREAD

**Issue by ruPaladin** [NoImageAvailable/CombatExtended#880]
Mods:
Core
HugsLib
Combat Extended

Spawn centipede on map. Its weapon will be replaced with new/old texture. Texture of Doomsday rocket launcher is replace with RPG texture. Without HugsLib textures are not replaced.

**Comment by LockdownX7** [comment]
Not finding any issues with the mentioned textures, with or without HugsLib loaded.

For clarity, the texture CE uses for the doomsday launcher is not the RPG's, they're similar but not identical:
![image](https://user-images.githubusercontent.com/20837685/68549304-98dde480-03ee-11ea-8f2c-d532124c8618.png)

You're free to reopen the issue if you provide detailed specifics on what the problem is, but as of now I'm not seeing anything wrong here.
